import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 10,
  },
  imageContainer: {
    position: "relative",
    width: "100%",
    height: 300,
    borderRadius: 10,
    overflow: "hidden",
    backgroundColor: "#fff",
  },
  scrollView: {
    height: 500,
  },
  imageWrapper: {
    width: 340,
    height: 250,
    marginRight: 10,
    marginTop: 40,
    marginLeft: 10,
  },
  image: {
    width: "100%",
    height: "100%",
    borderRadius: 20,
  },
  iconHeart: {
    position: "absolute",
    top: 3,
    right: 10,
  },
  title: {
    fontFamily: "ManropeRegular",
    fontSize: 50,
    fontWeight: "300",
    lineHeight: 63,
    letterSpacing: 0,
  },
  price: {
    fontFamily: "ManropeBold",
    fontSize: 16,
    fontWeight: "400",
    lineHeight: 24,
    letterSpacing: 0.05,
    color: "#2A4BA0",
  },
  description: {
    fontFamily: "ManropeRegular",
    fontSize: 16,
    fontWeight: "400",
    lineHeight: 24,
    letterSpacing: 0,
    textAlign: "left",
    color: "#A9B4BC",
  },
  brand: {
    fontFamily: "ManropeBold",
    fontSize: 50,
    fontWeight: "800",
    lineHeight: 63,
    letterSpacing: 0,
  },
  ratingContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    marginTop: 10,
    rowGap: 10,
  },
  rating: {
    fontFamily: "ManropeLight",
    fontSize: 14,
    fontWeight: "400",
    lineHeight: 20,
    letterSpacing: 0,
    textAlign: "center",
    marginLeft: 10,
  },
  discount: {
    fontFamily: "ManropeLight",
    fontSize: 14,
    fontWeight: "500",
    lineHeight: 20,
    letterSpacing: 0,
    textAlign: "center",
    color: "#F8F9FB",
    backgroundColor: "#2A4BA0",
    padding: 5,
    borderRadius: 15,
    paddingHorizontal: 10,
  },
  details: {
    fontFamily: "ManropesemiBold",
    fontSize: 16,
    fontWeight: "400",
    lineHeight: 24,
    letterSpacing: 0,
    textAlign: "left",
    marginBottom: 10,
  },
  imageView: {
    height: 5,
    width: 20,
    borderRadius: 5,
    margin: 5,
  },
  cartBtnOuter: {
    backgroundColor: "white",
    borderColor: "#2A4BA0",
    borderWidth: 1,
    borderRadius: 15,
    padding: 10,
    width: 100,
    alignItems: "center",
  },
  cartBtnInner: {
    color: "#2A4BA0",
    fontFamily: "ManropeRegular",
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 19,
    letterSpacing: 0,
    textAlign: "center",
  },
  buyBtnOuter: {
    backgroundColor: "#2A4BA0",
    borderRadius: 15,
    padding: 10,
    width: 100,
    alignItems: "center",
  },
  buyBtnInner: {
    color: "white",
    fontFamily: "ManropeRegular",
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 19,
    letterSpacing: 0,
    textAlign: "center",
  },
  cartBtnOuterInCart: {
    backgroundColor: "#2A4BA0",
    borderColor: "#2A4BA0",
    borderWidth: 1,
    borderRadius: 15,
    padding: 10,
    width: 100,
    alignItems: "center",
  },
  cartBtnIncart: {
    color: "white",
  },
  flexRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 5,
  },
  detailsContainer: {
    marginTop: 2,
    marginBottom: 5,
  },
});

export default styles;
